export interface AsmaulHusna {
  index: number;
  latin: string;
  arabic: string;
  translation_id: string;
  translation_en: string;
}

export const asmaulHusnaList: AsmaulHusna[] = [
  {
    index: 1,
    latin: "Ar Rahman",
    arabic: "الرَّحْمَنُ",
    translation_id: "Yang Maha Pengasih",
    translation_en: "The Most Gracious",
  },
  {
    index: 2,
    latin: "Ar Rahim",
    arabic: "الرَّحِيمُ",
    translation_id: "Yang Maha Penyayang",
    translation_en: "The Most Merciful",
  },
  {
    index: 3,
    latin: "Al Malik",
    arabic: "الْمَلِكُ",
    translation_id: "Yang Maha Merajai",
    translation_en: "The King",
  },
  {
    index: 4,
    latin: "Al Quddus",
    arabic: "الْقُدُّوسُ",
    translation_id: "Yang Maha Suci",
    translation_en: "The Most Holy",
  },
  {
    index: 5,
    latin: "As Salam",
    arabic: "السَّلَامُ",
    translation_id: "Yang Maha Memberi Kesejahteraan",
    translation_en: "The Source of Peace",
  },
  {
    index: 6,
    latin: "Al Mu'min",
    arabic: "الْمُؤْمِنُ",
    translation_id: "Yang Maha Memberi Keamanan",
    translation_en: "The Guardian of Faith",
  },
  {
    index: 7,
    latin: "Al Muhaimin",
    arabic: "الْمُهَيْمِنُ",
    translation_id: "Yang Maha Pemelihara",
    translation_en: "The Protector",
  },
  {
    index: 8,
    latin: "Al Aziz",
    arabic: "الْعَزِيزُ",
    translation_id: "Yang Maha Perkasa",
    translation_en: "The Almighty",
  },
  {
    index: 9,
    latin: "Al Jabbar",
    arabic: "الْجَبَّارُ",
    translation_id: "Yang Maha Memiliki Mutlak Kegagahan",
    translation_en: "The Compeller",
  },
  {
    index: 10,
    latin: "Al Mutakabbir",
    arabic: "الْمُتَكَبِّرُ",
    translation_id: "Yang Maha Megah",
    translation_en: "The Majestic",
  },
  {
    index: 11,
    latin: "Al Khaliq",
    arabic: "الْخَالِقُ",
    translation_id: "Yang Maha Pencipta",
    translation_en: "The Creator",
  },
  {
    index: 12,
    latin: "Al Baari",
    arabic: "الْبَارِئُ",
    translation_id: "Yang Maha Melepaskan",
    translation_en: "The Evolver",
  },
  {
    index: 13,
    latin: "Al Musawwir",
    arabic: "الْمُصَوِّرُ",
    translation_id: "Yang Maha Membentuk Rupa",
    translation_en: "The Fashioner",
  },
  {
    index: 14,
    latin: "Al Ghaffar",
    arabic: "الْغَفَّارُ",
    translation_id: "Yang Maha Pengampun",
    translation_en: "The Forgiver",
  },
  {
    index: 15,
    latin: "Al Qahhar",
    arabic: "الْقَهَّارُ",
    translation_id: "Yang Maha Memaksa",
    translation_en: "The Subduer",
  },
  {
    index: 16,
    latin: "Al Wahhab",
    arabic: "الْوَهَّابُ",
    translation_id: "Yang Maha Pemberi Karunia",
    translation_en: "The Bestower",
  },
  {
    index: 17,
    latin: "Ar Razzaq",
    arabic: "الرَّزَّاقُ",
    translation_id: "Yang Maha Pemberi Rezeki",
    translation_en: "The Provider",
  },
  {
    index: 18,
    latin: "Al Fattah",
    arabic: "الْفَتَّاحُ",
    translation_id: "Yang Maha Pembuka Rahmat",
    translation_en: "The Opener",
  },
  {
    index: 19,
    latin: "Al 'Alim",
    arabic: "الْعَلِيمُ",
    translation_id: "Yang Maha Mengetahui",
    translation_en: "The All-Knowing",
  },
  {
    index: 20,
    latin: "Al Qabidh",
    arabic: "الْقَابِضُ",
    translation_id: "Yang Maha Menyempitkan",
    translation_en: "The Constrictor",
  },
  {
    index: 21,
    latin: "Al Basit",
    arabic: "الْبَاسِطُ",
    translation_id: "Yang Maha Melapangkan",
    translation_en: "The Expander",
  },
  {
    index: 22,
    latin: "Al Khafidh",
    arabic: "الْخَافِضُ",
    translation_id: "Yang Maha Merendahkan",
    translation_en: "The Abaser",
  },
  {
    index: 23,
    latin: "Ar Rafi'",
    arabic: "الرَّافِعُ",
    translation_id: "Yang Maha Meninggikan",
    translation_en: "The Exalter",
  },
  {
    index: 24,
    latin: "Al Mu'izz",
    arabic: "الْمُعِزُّ",
    translation_id: "Yang Maha Memuliakan",
    translation_en: "The Bestower of Honors",
  },
  {
    index: 25,
    latin: "Al Mudzill",
    arabic: "الْمُذِلُّ",
    translation_id: "Yang Maha Menghinakan",
    translation_en: "The Dishonorer",
  },
  {
    index: 26,
    latin: "As Sami'",
    arabic: "السَّمِيعُ",
    translation_id: "Yang Maha Mendengar",
    translation_en: "The All-Hearing",
  },
  {
    index: 27,
    latin: "Al Bashir",
    arabic: "الْبَصِيرُ",
    translation_id: "Yang Maha Melihat",
    translation_en: "The All-Seeing",
  },
  {
    index: 28,
    latin: "Al Hakam",
    arabic: "الْحَكَمُ",
    translation_id: "Yang Maha Menetapkan",
    translation_en: "The Judge",
  },
  {
    index: 29,
    latin: "Al 'Adl",
    arabic: "الْعَدْلُ",
    translation_id: "Yang Maha Adil",
    translation_en: "The Just",
  },
  {
    index: 30,
    latin: "Al Latif",
    arabic: "اللَّطِيفُ",
    translation_id: "Yang Maha Lembut",
    translation_en: "The Subtle One",
  },
  {
    index: 31,
    latin: "Al Khabir",
    arabic: "الْخَبِيرُ",
    translation_id: "Yang Maha Mengenal",
    translation_en: "The All-Aware",
  },
  {
    index: 32,
    latin: "Al Halim",
    arabic: "الْحَلِيمُ",
    translation_id: "Yang Maha Penyantun",
    translation_en: "The Forbearing",
  },
  {
    index: 33,
    latin: "Al 'Azhim",
    arabic: "الْعَظِيمُ",
    translation_id: "Yang Maha Agung",
    translation_en: "The Magnificent",
  },
  {
    index: 34,
    latin: "Al Ghafur",
    arabic: "الْغَفُورُ",
    translation_id: "Yang Maha Pengampun",
    translation_en: "The Forgiver",
  },
  {
    index: 35,
    latin: "Ash Shakur",
    arabic: "الشَّكُورُ",
    translation_id: "Yang Maha Pembalas Budi",
    translation_en: "The Appreciative",
  },
  {
    index: 36,
    latin: "Al 'Aliy",
    arabic: "الْعَلِيُّ",
    translation_id: "Yang Maha Tinggi",
    translation_en: "The Most High",
  },
  {
    index: 37,
    latin: "Al Kabir",
    arabic: "الْكَبِيرُ",
    translation_id: "Yang Maha Besar",
    translation_en: "The Most Great",
  },
  {
    index: 38,
    latin: "Al Hafizh",
    arabic: "الْحَفِيظُ",
    translation_id: "Yang Maha Memelihara",
    translation_en: "The Preserver",
  },
  {
    index: 39,
    latin: "Al Muqit",
    arabic: "الْمُقِيتُ",
    translation_id: "Yang Maha Pemberi Kecukupan",
    translation_en: "The Maintainer",
  },
  {
    index: 40,
    latin: "Al Hasib",
    arabic: "الْحَسِيبُ",
    translation_id: "Yang Maha Membuat Perhitungan",
    translation_en: "The Reckoner",
  },
  {
    index: 41,
    latin: "Al Jalil",
    arabic: "الْجَلِيلُ",
    translation_id: "Yang Maha Luhur",
    translation_en: "The Sublime One",
  },
  {
    index: 42,
    latin: "Al Karim",
    arabic: "الْكَرِيمُ",
    translation_id: "Yang Maha Pemurah",
    translation_en: "The Generous One",
  },
  {
    index: 43,
    latin: "Ar Raqib",
    arabic: "الرَّقِيبُ",
    translation_id: "Yang Maha Mengawasi",
    translation_en: "The Watchful",
  },
  {
    index: 44,
    latin: "Al Mujib",
    arabic: "الْمُجِيبُ",
    translation_id: "Yang Maha Mengabulkan",
    translation_en: "The Responsive",
  },
  {
    index: 45,
    latin: "Al Wasi'",
    arabic: "الْوَاسِعُ",
    translation_id: "Yang Maha Luas",
    translation_en: "The All-Encompassing",
  },
  {
    index: 46,
    latin: "Al Hakim",
    arabic: "الْحَكِيمُ",
    translation_id: "Yang Maha Bijaksana",
    translation_en: "The Wise",
  },
  {
    index: 47,
    latin: "Al Wadud",
    arabic: "الْوَدُودُ",
    translation_id: "Yang Maha Mengasihi",
    translation_en: "The Loving",
  },
  {
    index: 48,
    latin: "Al Majid",
    arabic: "الْمَجِيدُ",
    translation_id: "Yang Maha Mulia",
    translation_en: "The Glorious",
  },
  {
    index: 49,
    latin: "Al Ba'its",
    arabic: "الْبَاعِثُ",
    translation_id: "Yang Maha Membangkitkan",
    translation_en: "The Resurrecting",
  },
  {
    index: 50,
    latin: "Ash Shahid",
    arabic: "الشَّهِيدُ",
    translation_id: "Yang Maha Menyaksikan",
    translation_en: "The Witness",
  },
  {
    index: 51,
    latin: "Al Haqq",
    arabic: "الْحَقُّ",
    translation_id: "Yang Maha Benar",
    translation_en: "The Truth",
  },
  {
    index: 52,
    latin: "Al Wakil",
    arabic: "الْوَكِيلُ",
    translation_id: "Yang Maha Memelihara",
    translation_en: "The Trustee",
  },
  {
    index: 53,
    latin: "Al Qawiyy",
    arabic: "الْقَوِيُّ",
    translation_id: "Yang Maha Kuat",
    translation_en: "The Strong",
  },
  {
    index: 54,
    latin: "Al Matin",
    arabic: "الْمَتِينُ",
    translation_id: "Yang Maha Kokoh",
    translation_en: "The Firm",
  },
  {
    index: 55,
    latin: "Al Waliyy",
    arabic: "الْوَلِيُّ",
    translation_id: "Yang Maha Melindungi",
    translation_en: "The Protecting Friend",
  },
  {
    index: 56,
    latin: "Al Hamid",
    arabic: "الْحَمِيدُ",
    translation_id: "Yang Maha Terpuji",
    translation_en: "The Praiseworthy",
  },
  {
    index: 57,
    latin: "Al Muhshi",
    arabic: "الْمُحْصِي",
    translation_id: "Yang Maha Menghitung",
    translation_en: "The Counter",
  },
  {
    index: 58,
    latin: "Al Mubdi'",
    arabic: "الْمُبْدِئُ",
    translation_id: "Yang Maha Memulai",
    translation_en: "The Originator",
  },
  {
    index: 59,
    latin: "Al Mu'id",
    arabic: "الْمُعِيدُ",
    translation_id: "Yang Maha Mengembalikan",
    translation_en: "The Restorer",
  },
  {
    index: 60,
    latin: "Al Muhyi",
    arabic: "الْمُحْيِي",
    translation_id: "Yang Maha Menghidupkan",
    translation_en: "The Giver of Life",
  },
  {
    index: 61,
    latin: "Al Mumit",
    arabic: "الْمُمِيتُ",
    translation_id: "Yang Maha Mematikan",
    translation_en: "The Destroyer",
  },
  {
    index: 62,
    latin: "Al Hayyu",
    arabic: "الْحَيُّ",
    translation_id: "Yang Maha Hidup",
    translation_en: "The Living",
  },
  {
    index: 63,
    latin: "Al Qayyum",
    arabic: "الْقَيُّومُ",
    translation_id: "Yang Maha Mandiri",
    translation_en: "The Self-Subsisting",
  },
  {
    index: 64,
    latin: "Al Wajid",
    arabic: "الْوَاجِدُ",
    translation_id: "Yang Maha Penemu",
    translation_en: "The Finder",
  },
  {
    index: 65,
    latin: "Al Majid",
    arabic: "الْمَاجِدُ",
    translation_id: "Yang Maha Mulia",
    translation_en: "The Noble",
  },
  {
    index: 66,
    latin: "Al Wahid",
    arabic: "الْوَاحِدُ",
    translation_id: "Yang Maha Tunggal",
    translation_en: "The One",
  },
  {
    index: 67,
    latin: "Al Ahad",
    arabic: "الْأَحَدُ",
    translation_id: "Yang Maha Esa",
    translation_en: "The Unity",
  },
  {
    index: 68,
    latin: "Ash Shamad",
    arabic: "الصَّمَدُ",
    translation_id: "Yang Maha Dibutuhkan",
    translation_en: "The Eternal",
  },
  {
    index: 69,
    latin: "Al Qadir",
    arabic: "الْقَادِرُ",
    translation_id: "Yang Maha Menentukan",
    translation_en: "The Able",
  },
  {
    index: 70,
    latin: "Al Muqtadir",
    arabic: "الْمُقْتَدِرُ",
    translation_id: "Yang Maha Berkuasa",
    translation_en: "The Powerful",
  },
  {
    index: 71,
    latin: "Al Muqaddim",
    arabic: "الْمُقَدِّمُ",
    translation_id: "Yang Maha Mendahulukan",
    translation_en: "The Expediter",
  },
  {
    index: 72,
    latin: "Al Mu'akhkhir",
    arabic: "الْمُؤَخِّرُ",
    translation_id: "Yang Maha Mengakhirkan",
    translation_en: "The Delayer",
  },
  {
    index: 73,
    latin: "Al Awwal",
    arabic: "الْأَوَّلُ",
    translation_id: "Yang Maha Awal",
    translation_en: "The First",
  },
  {
    index: 74,
    latin: "Al Akhir",
    arabic: "الْآخِرُ",
    translation_id: "Yang Maha Akhir",
    translation_en: "The Last",
  },
  {
    index: 75,
    latin: "Az Zhahir",
    arabic: "الظَّاهِرُ",
    translation_id: "Yang Maha Nyata",
    translation_en: "The Manifest",
  },
  {
    index: 76,
    latin: "Al Batin",
    arabic: "الْبَاطِنُ",
    translation_id: "Yang Maha Ghaib",
    translation_en: "The Hidden",
  },
  {
    index: 77,
    latin: "Al Wali",
    arabic: "الْوَالِي",
    translation_id: "Yang Maha Memerintah",
    translation_en: "The Governor",
  },
  {
    index: 78,
    latin: "Al Muta'ali",
    arabic: "الْمُتَعَالِي",
    translation_id: "Yang Maha Tinggi",
    translation_en: "The Most Exalted",
  },
  {
    index: 79,
    latin: "Al Barr",
    arabic: "الْبَرُّ",
    translation_id: "Yang Maha Penderma",
    translation_en: "The Source of Goodness",
  },
  {
    index: 80,
    latin: "At Tawwab",
    arabic: "التَّوَّابُ",
    translation_id: "Yang Maha Penerima Taubat",
    translation_en: "The Acceptor of Repentance",
  },
  {
    index: 81,
    latin: "Al Muntaqim",
    arabic: "الْمُنْتَقِمُ",
    translation_id: "Yang Maha Pemberi Balasan",
    translation_en: "The Avenger",
  },
  {
    index: 82,
    latin: "Al 'Afuww",
    arabic: "الْعَفُوُّ",
    translation_id: "Yang Maha Pemaaf",
    translation_en: "The Pardoner",
  },
  {
    index: 83,
    latin: "Ar Ra'uf",
    arabic: "الرَّؤُوفُ",
    translation_id: "Yang Maha Pengasuh",
    translation_en: "The Compassionate",
  },
  {
    index: 84,
    latin: "Malikul Mulk",
    arabic: "مَالِكُ الْمُلْكِ",
    translation_id: "Yang Maha Penguasa Kerajaan",
    translation_en: "The Owner of All Sovereignty",
  },
  {
    index: 85,
    latin: "Dzul Jalali Wal Ikram",
    arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ",
    translation_id: "Yang Maha Pemilik Kebesaran dan Kemuliaan",
    translation_en: "The Lord of Majesty and Generosity",
  },
  {
    index: 86,
    latin: "Al Muqsit",
    arabic: "الْمُقْسِطُ",
    translation_id: "Yang Maha Pemberi Keadilan",
    translation_en: "The Equitable",
  },
  {
    index: 87,
    latin: "Al Jami'",
    arabic: "الْجَامِعُ",
    translation_id: "Yang Maha Mengumpulkan",
    translation_en: "The Gatherer",
  },
  {
    index: 88,
    latin: "Al Ghaniyy",
    arabic: "الْغَنِيُّ",
    translation_id: "Yang Maha Kaya",
    translation_en: "The Self-Sufficient",
  },
  {
    index: 89,
    latin: "Al Mughni",
    arabic: "الْمُغْنِي",
    translation_id: "Yang Maha Pemberi Kekayaan",
    translation_en: "The Enricher",
  },
  {
    index: 90,
    latin: "Al Mani'",
    arabic: "الْمَانِعُ",
    translation_id: "Yang Maha Mencegah",
    translation_en: "The Withholder",
  },
  {
    index: 91,
    latin: "Ad Darr",
    arabic: "الضَّارُّ",
    translation_id: "Yang Maha Penimpa Kemudharatan",
    translation_en: "The Distresser",
  },
  {
    index: 92,
    latin: "An Nafi'",
    arabic: "النَّافِعُ",
    translation_id: "Yang Maha Memberi Manfaat",
    translation_en: "The Propitious",
  },
  {
    index: 93,
    latin: "An Nur",
    arabic: "النُّورُ",
    translation_id: "Yang Maha Bercahaya",
    translation_en: "The Light",
  },
  {
    index: 94,
    latin: "Al Hadi",
    arabic: "الْهَادِي",
    translation_id: "Yang Maha Pemberi Petunjuk",
    translation_en: "The Guide",
  },
  {
    index: 95,
    latin: "Al Badi'",
    arabic: "الْبَدِيعُ",
    translation_id: "Yang Maha Pencipta",
    translation_en: "The Incomparable",
  },
  {
    index: 96,
    latin: "Al Baqi",
    arabic: "الْبَاقِي",
    translation_id: "Yang Maha Kekal",
    translation_en: "The Everlasting",
  },
  {
    index: 97,
    latin: "Al Warits",
    arabic: "الْوَارِثُ",
    translation_id: "Yang Maha Pewaris",
    translation_en: "The Heir",
  },
  {
    index: 98,
    latin: "Ar Rashid",
    arabic: "الرَّشِيدُ",
    translation_id: "Yang Maha Pandai",
    translation_en: "The Guide to the Right Path",
  },
  {
    index: 99,
    latin: "As Sabur",
    arabic: "الصَّبُورُ",
    translation_id: "Yang Maha Sabar",
    translation_en: "The Patient",
  },
];
