export interface SurahInfo {
  nomor: number;
  nama: string;
  nama_latin: string;
  jumlah_ayat: number;
  tempat_turun: string;
  arti: string;
}

export const surahList: SurahInfo[] = [
  {
    nomor: 1,
    nama: "الفاتحة",
    nama_latin: "Al-Fatihah",
    jumlah_ayat: 7,
    tempat_turun: "Mekah",
    arti: "Pembukaan",
  },
  {
    nomor: 2,
    nama: "البقرة",
    nama_latin: "Al-Baqarah",
    jumlah_ayat: 286,
    tempat_turun: "Madinah",
    arti: "Sapi Betina",
  },
  {
    nomor: 3,
    nama: "آل عمران",
    nama_latin: "Ali 'Imran",
    jumlah_ayat: 200,
    tempat_turun: "Madinah",
    arti: "Keluarga Imran",
  },
  {
    nomor: 4,
    nama: "النساء",
    nama_latin: "An-Nisa'",
    jumlah_ayat: 176,
    tempat_turun: "Madinah",
    arti: "Wanita",
  },
  {
    nomor: 5,
    nama: "المائدة",
    nama_latin: "Al-Ma'idah",
    jumlah_ayat: 120,
    tempat_turun: "Madinah",
    arti: "Hidangan",
  },
  {
    nomor: 6,
    nama: "الأنعام",
    nama_latin: "Al-An'am",
    jumlah_ayat: 165,
    tempat_turun: "Mekah",
    arti: "Binatang Ternak",
  },
  {
    nomor: 7,
    nama: "الأعراف",
    nama_latin: "Al-A'raf",
    jumlah_ayat: 206,
    tempat_turun: "Mekah",
    arti: "Tempat Tertinggi",
  },
  {
    nomor: 8,
    nama: "الأنفال",
    nama_latin: "Al-Anfal",
    jumlah_ayat: 75,
    tempat_turun: "Madinah",
    arti: "Harta Rampasan Perang",
  },
  {
    nomor: 9,
    nama: "التوبة",
    nama_latin: "At-Taubah",
    jumlah_ayat: 129,
    tempat_turun: "Madinah",
    arti: "Pengampunan",
  },
  {
    nomor: 10,
    nama: "يونس",
    nama_latin: "Yunus",
    jumlah_ayat: 109,
    tempat_turun: "Mekah",
    arti: "Yunus",
  },
  {
    nomor: 11,
    nama: "هود",
    nama_latin: "Hud",
    jumlah_ayat: 123,
    tempat_turun: "Mekah",
    arti: "Hud",
  },
  {
    nomor: 12,
    nama: "يوسف",
    nama_latin: "Yusuf",
    jumlah_ayat: 111,
    tempat_turun: "Mekah",
    arti: "Yusuf",
  },
  {
    nomor: 13,
    nama: "الرعد",
    nama_latin: "Ar-Ra'd",
    jumlah_ayat: 43,
    tempat_turun: "Madinah",
    arti: "Guruh",
  },
  {
    nomor: 14,
    nama: "إبراهيم",
    nama_latin: "Ibrahim",
    jumlah_ayat: 52,
    tempat_turun: "Mekah",
    arti: "Ibrahim",
  },
  {
    nomor: 15,
    nama: "الحجر",
    nama_latin: "Al-Hijr",
    jumlah_ayat: 99,
    tempat_turun: "Mekah",
    arti: "Negeri Kaum Samud",
  },
  {
    nomor: 16,
    nama: "النحل",
    nama_latin: "An-Nahl",
    jumlah_ayat: 128,
    tempat_turun: "Mekah",
    arti: "Lebah",
  },
  {
    nomor: 17,
    nama: "الإسراء",
    nama_latin: "Al-Isra'",
    jumlah_ayat: 111,
    tempat_turun: "Mekah",
    arti: "Perjalanan Malam",
  },
  {
    nomor: 18,
    nama: "الكهف",
    nama_latin: "Al-Kahf",
    jumlah_ayat: 110,
    tempat_turun: "Mekah",
    arti: "Gua",
  },
  {
    nomor: 19,
    nama: "مريم",
    nama_latin: "Maryam",
    jumlah_ayat: 98,
    tempat_turun: "Mekah",
    arti: "Maryam",
  },
  {
    nomor: 20,
    nama: "طه",
    nama_latin: "Ta Ha",
    jumlah_ayat: 135,
    tempat_turun: "Mekah",
    arti: "Ta Ha",
  },
  {
    nomor: 21,
    nama: "الأنبياء",
    nama_latin: "Al-Anbiya'",
    jumlah_ayat: 112,
    tempat_turun: "Mekah",
    arti: "Para Nabi",
  },
  {
    nomor: 22,
    nama: "الحج",
    nama_latin: "Al-Hajj",
    jumlah_ayat: 78,
    tempat_turun: "Madinah",
    arti: "Haji",
  },
  {
    nomor: 23,
    nama: "المؤمنون",
    nama_latin: "Al-Mu'minun",
    jumlah_ayat: 118,
    tempat_turun: "Mekah",
    arti: "Orang-orang Mukmin",
  },
  {
    nomor: 24,
    nama: "النور",
    nama_latin: "An-Nur",
    jumlah_ayat: 64,
    tempat_turun: "Madinah",
    arti: "Cahaya",
  },
  {
    nomor: 25,
    nama: "الفرقان",
    nama_latin: "Al-Furqan",
    jumlah_ayat: 77,
    tempat_turun: "Mekah",
    arti: "Pembeda",
  },
  {
    nomor: 26,
    nama: "الشعراء",
    nama_latin: "Asy-Syu'ara'",
    jumlah_ayat: 227,
    tempat_turun: "Mekah",
    arti: "Para Penyair",
  },
  {
    nomor: 27,
    nama: "النمل",
    nama_latin: "An-Naml",
    jumlah_ayat: 93,
    tempat_turun: "Mekah",
    arti: "Semut",
  },
  {
    nomor: 28,
    nama: "القصص",
    nama_latin: "Al-Qasas",
    jumlah_ayat: 88,
    tempat_turun: "Mekah",
    arti: "Kisah-Kisah",
  },
  {
    nomor: 29,
    nama: "العنكبوت",
    nama_latin: "Al-'Ankabut",
    jumlah_ayat: 69,
    tempat_turun: "Mekah",
    arti: "Laba-Laba",
  },
  {
    nomor: 30,
    nama: "الروم",
    nama_latin: "Ar-Rum",
    jumlah_ayat: 60,
    tempat_turun: "Mekah",
    arti: "Romawi",
  },
  {
    nomor: 31,
    nama: "لقمان",
    nama_latin: "Luqman",
    jumlah_ayat: 34,
    tempat_turun: "Mekah",
    arti: "Luqman",
  },
  {
    nomor: 32,
    nama: "السجدة",
    nama_latin: "As-Sajdah",
    jumlah_ayat: 30,
    tempat_turun: "Mekah",
    arti: "Sujud",
  },
  {
    nomor: 33,
    nama: "الأحزاب",
    nama_latin: "Al-Ahzab",
    jumlah_ayat: 73,
    tempat_turun: "Madinah",
    arti: "Golongan-Golongan",
  },
  {
    nomor: 34,
    nama: "سبأ",
    nama_latin: "Saba'",
    jumlah_ayat: 54,
    tempat_turun: "Mekah",
    arti: "Saba'",
  },
  {
    nomor: 35,
    nama: "فاطر",
    nama_latin: "Fatir",
    jumlah_ayat: 45,
    tempat_turun: "Mekah",
    arti: "Pencipta",
  },
  {
    nomor: 36,
    nama: "يس",
    nama_latin: "Ya Sin",
    jumlah_ayat: 83,
    tempat_turun: "Mekah",
    arti: "Ya Sin",
  },
  {
    nomor: 37,
    nama: "الصافات",
    nama_latin: "As-Saffat",
    jumlah_ayat: 182,
    tempat_turun: "Mekah",
    arti: "Yang Berbaris",
  },
  {
    nomor: 38,
    nama: "ص",
    nama_latin: "Sad",
    jumlah_ayat: 88,
    tempat_turun: "Mekah",
    arti: "Sad",
  },
  {
    nomor: 39,
    nama: "الزمر",
    nama_latin: "Az-Zumar",
    jumlah_ayat: 75,
    tempat_turun: "Mekah",
    arti: "Rombongan",
  },
  {
    nomor: 40,
    nama: "غافر",
    nama_latin: "Ghafir",
    jumlah_ayat: 85,
    tempat_turun: "Mekah",
    arti: "Yang Mengampuni",
  },
  {
    nomor: 41,
    nama: "فصلت",
    nama_latin: "Fussilat",
    jumlah_ayat: 54,
    tempat_turun: "Mekah",
    arti: "Yang Dijelaskan",
  },
  {
    nomor: 42,
    nama: "الشورى",
    nama_latin: "Asy-Syura",
    jumlah_ayat: 53,
    tempat_turun: "Mekah",
    arti: "Musyawarah",
  },
  {
    nomor: 43,
    nama: "الزخرف",
    nama_latin: "Az-Zukhruf",
    jumlah_ayat: 89,
    tempat_turun: "Mekah",
    arti: "Perhiasan",
  },
  {
    nomor: 44,
    nama: "الدخان",
    nama_latin: "Ad-Dukhan",
    jumlah_ayat: 59,
    tempat_turun: "Mekah",
    arti: "Kabut",
  },
  {
    nomor: 45,
    nama: "الجاثية",
    nama_latin: "Al-Jasiyah",
    jumlah_ayat: 37,
    tempat_turun: "Mekah",
    arti: "Yang Berlutut",
  },
  {
    nomor: 46,
    nama: "الأحقاف",
    nama_latin: "Al-Ahqaf",
    jumlah_ayat: 35,
    tempat_turun: "Mekah",
    arti: "Bukit Pasir",
  },
  {
    nomor: 47,
    nama: "محمد",
    nama_latin: "Muhammad",
    jumlah_ayat: 38,
    tempat_turun: "Madinah",
    arti: "Muhammad",
  },
  {
    nomor: 48,
    nama: "الفتح",
    nama_latin: "Al-Fath",
    jumlah_ayat: 29,
    tempat_turun: "Madinah",
    arti: "Kemenangan",
  },
  {
    nomor: 49,
    nama: "الحجرات",
    nama_latin: "Al-Hujurat",
    jumlah_ayat: 18,
    tempat_turun: "Madinah",
    arti: "Kamar-Kamar",
  },
  {
    nomor: 50,
    nama: "ق",
    nama_latin: "Qaf",
    jumlah_ayat: 45,
    tempat_turun: "Mekah",
    arti: "Qaf",
  },
  {
    nomor: 51,
    nama: "الذاريات",
    nama_latin: "Az-Zariyat",
    jumlah_ayat: 60,
    tempat_turun: "Mekah",
    arti: "Angin yang Menerbangkan",
  },
  {
    nomor: 52,
    nama: "الطور",
    nama_latin: "At-Tur",
    jumlah_ayat: 49,
    tempat_turun: "Mekah",
    arti: "Bukit Tursina",
  },
  {
    nomor: 53,
    nama: "النجم",
    nama_latin: "An-Najm",
    jumlah_ayat: 62,
    tempat_turun: "Mekah",
    arti: "Bintang",
  },
  {
    nomor: 54,
    nama: "القمر",
    nama_latin: "Al-Qamar",
    jumlah_ayat: 55,
    tempat_turun: "Mekah",
    arti: "Bulan",
  },
  {
    nomor: 55,
    nama: "الرحمن",
    nama_latin: "Ar-Rahman",
    jumlah_ayat: 78,
    tempat_turun: "Madinah",
    arti: "Yang Maha Pengasih",
  },
  {
    nomor: 56,
    nama: "الواقعة",
    nama_latin: "Al-Waqi'ah",
    jumlah_ayat: 96,
    tempat_turun: "Mekah",
    arti: "Hari Kiamat",
  },
  {
    nomor: 57,
    nama: "الحديد",
    nama_latin: "Al-Hadid",
    jumlah_ayat: 29,
    tempat_turun: "Madinah",
    arti: "Besi",
  },
  {
    nomor: 58,
    nama: "المجادلة",
    nama_latin: "Al-Mujadalah",
    jumlah_ayat: 22,
    tempat_turun: "Madinah",
    arti: "Wanita yang Mengajukan Gugatan",
  },
  {
    nomor: 59,
    nama: "الحشر",
    nama_latin: "Al-Hasyr",
    jumlah_ayat: 24,
    tempat_turun: "Madinah",
    arti: "Pengusiran",
  },
  {
    nomor: 60,
    nama: "الممتحنة",
    nama_latin: "Al-Mumtahanah",
    jumlah_ayat: 13,
    tempat_turun: "Madinah",
    arti: "Perempuan yang Diuji",
  },
  {
    nomor: 61,
    nama: "الصف",
    nama_latin: "As-Saff",
    jumlah_ayat: 14,
    tempat_turun: "Madinah",
    arti: "Barisan",
  },
  {
    nomor: 62,
    nama: "الجمعة",
    nama_latin: "Al-Jumu'ah",
    jumlah_ayat: 11,
    tempat_turun: "Madinah",
    arti: "Hari Jum'at",
  },
  {
    nomor: 63,
    nama: "المنافقون",
    nama_latin: "Al-Munafiqun",
    jumlah_ayat: 11,
    tempat_turun: "Madinah",
    arti: "Orang-Orang Munafik",
  },
  {
    nomor: 64,
    nama: "التغابن",
    nama_latin: "At-Tagabun",
    jumlah_ayat: 18,
    tempat_turun: "Madinah",
    arti: "Hari Pengungkapan Kesalahan",
  },
  {
    nomor: 65,
    nama: "الطلاق",
    nama_latin: "At-Talaq",
    jumlah_ayat: 12,
    tempat_turun: "Madinah",
    arti: "Talak",
  },
  {
    nomor: 66,
    nama: "التحريم",
    nama_latin: "At-Tahrim",
    jumlah_ayat: 12,
    tempat_turun: "Madinah",
    arti: "Pengharaman",
  },
  {
    nomor: 67,
    nama: "الملك",
    nama_latin: "Al-Mulk",
    jumlah_ayat: 30,
    tempat_turun: "Mekah",
    arti: "Kerajaan",
  },
  {
    nomor: 68,
    nama: "القلم",
    nama_latin: "Al-Qalam",
    jumlah_ayat: 52,
    tempat_turun: "Mekah",
    arti: "Pena",
  },
  {
    nomor: 69,
    nama: "الحاقة",
    nama_latin: "Al-Haqqah",
    jumlah_ayat: 52,
    tempat_turun: "Mekah",
    arti: "Hari Kiamat",
  },
  {
    nomor: 70,
    nama: "المعارج",
    nama_latin: "Al-Ma'arij",
    jumlah_ayat: 44,
    tempat_turun: "Mekah",
    arti: "Tempat-Tempat Naik",
  },
  {
    nomor: 71,
    nama: "نوح",
    nama_latin: "Nuh",
    jumlah_ayat: 28,
    tempat_turun: "Mekah",
    arti: "Nuh",
  },
  {
    nomor: 72,
    nama: "الجن",
    nama_latin: "Al-Jinn",
    jumlah_ayat: 28,
    tempat_turun: "Mekah",
    arti: "Jin",
  },
  {
    nomor: 73,
    nama: "المزمل",
    nama_latin: "Al-Muzzammil",
    jumlah_ayat: 20,
    tempat_turun: "Mekah",
    arti: "Orang yang Berselimut",
  },
  {
    nomor: 74,
    nama: "المدثر",
    nama_latin: "Al-Muddassir",
    jumlah_ayat: 56,
    tempat_turun: "Mekah",
    arti: "Orang yang Berkemul",
  },
  {
    nomor: 75,
    nama: "القيامة",
    nama_latin: "Al-Qiyamah",
    jumlah_ayat: 40,
    tempat_turun: "Mekah",
    arti: "Hari Kiamat",
  },
  {
    nomor: 76,
    nama: "الإنسان",
    nama_latin: "Al-Insan",
    jumlah_ayat: 31,
    tempat_turun: "Madinah",
    arti: "Manusia",
  },
  {
    nomor: 77,
    nama: "المرسلات",
    nama_latin: "Al-Mursalat",
    jumlah_ayat: 50,
    tempat_turun: "Mekah",
    arti: "Malaikat yang Diutus",
  },
  {
    nomor: 78,
    nama: "النبأ",
    nama_latin: "An-Naba'",
    jumlah_ayat: 40,
    tempat_turun: "Mekah",
    arti: "Berita Besar",
  },
  {
    nomor: 79,
    nama: "النازعات",
    nama_latin: "An-Nazi'at",
    jumlah_ayat: 46,
    tempat_turun: "Mekah",
    arti: "Malaikat yang Mencabut",
  },
  {
    nomor: 80,
    nama: "عبس",
    nama_latin: "'Abasa",
    jumlah_ayat: 42,
    tempat_turun: "Mekah",
    arti: "Bermuka Masam",
  },
  {
    nomor: 81,
    nama: "التكوير",
    nama_latin: "At-Takwir",
    jumlah_ayat: 29,
    tempat_turun: "Mekah",
    arti: "Menggulung",
  },
  {
    nomor: 82,
    nama: "الانفطار",
    nama_latin: "Al-Infitar",
    jumlah_ayat: 19,
    tempat_turun: "Mekah",
    arti: "Terbelah",
  },
  {
    nomor: 83,
    nama: "المطففين",
    nama_latin: "Al-Mutaffifin",
    jumlah_ayat: 36,
    tempat_turun: "Mekah",
    arti: "Orang-Orang Curang",
  },
  {
    nomor: 84,
    nama: "الانشقاق",
    nama_latin: "Al-Insyiqaq",
    jumlah_ayat: 25,
    tempat_turun: "Mekah",
    arti: "Terbelah",
  },
  {
    nomor: 85,
    nama: "البروج",
    nama_latin: "Al-Buruj",
    jumlah_ayat: 22,
    tempat_turun: "Mekah",
    arti: "Gugusan Bintang",
  },
  {
    nomor: 86,
    nama: "الطارق",
    nama_latin: "At-Tariq",
    jumlah_ayat: 17,
    tempat_turun: "Mekah",
    arti: "Yang Datang di Malam Hari",
  },
  {
    nomor: 87,
    nama: "الأعلى",
    nama_latin: "Al-A'la",
    jumlah_ayat: 19,
    tempat_turun: "Mekah",
    arti: "Yang Maha Tinggi",
  },
  {
    nomor: 88,
    nama: "الغاشية",
    nama_latin: "Al-Gasyiyah",
    jumlah_ayat: 26,
    tempat_turun: "Mekah",
    arti: "Hari Pembalasan",
  },
  {
    nomor: 89,
    nama: "الفجر",
    nama_latin: "Al-Fajr",
    jumlah_ayat: 30,
    tempat_turun: "Mekah",
    arti: "Fajar",
  },
  {
    nomor: 90,
    nama: "البلد",
    nama_latin: "Al-Balad",
    jumlah_ayat: 20,
    tempat_turun: "Mekah",
    arti: "Negeri",
  },
  {
    nomor: 91,
    nama: "الشمس",
    nama_latin: "Asy-Syams",
    jumlah_ayat: 15,
    tempat_turun: "Mekah",
    arti: "Matahari",
  },
  {
    nomor: 92,
    nama: "الليل",
    nama_latin: "Al-Lail",
    jumlah_ayat: 21,
    tempat_turun: "Mekah",
    arti: "Malam",
  },
  {
    nomor: 93,
    nama: "الضحى",
    nama_latin: "Ad-Duha",
    jumlah_ayat: 11,
    tempat_turun: "Mekah",
    arti: "Waktu Duha",
  },
  {
    nomor: 94,
    nama: "الشرح",
    nama_latin: "Al-Insyirah",
    jumlah_ayat: 8,
    tempat_turun: "Mekah",
    arti: "Melapangkan",
  },
  {
    nomor: 95,
    nama: "التين",
    nama_latin: "At-Tin",
    jumlah_ayat: 8,
    tempat_turun: "Mekah",
    arti: "Buah Tin",
  },
  {
    nomor: 96,
    nama: "العلق",
    nama_latin: "Al-'Alaq",
    jumlah_ayat: 19,
    tempat_turun: "Mekah",
    arti: "Segumpal Darah",
  },
  {
    nomor: 97,
    nama: "القدر",
    nama_latin: "Al-Qadr",
    jumlah_ayat: 5,
    tempat_turun: "Mekah",
    arti: "Kemuliaan",
  },
  {
    nomor: 98,
    nama: "البينة",
    nama_latin: "Al-Bayyinah",
    jumlah_ayat: 8,
    tempat_turun: "Madinah",
    arti: "Bukti Nyata",
  },
  {
    nomor: 99,
    nama: "الزلزلة",
    nama_latin: "Az-Zalzalah",
    jumlah_ayat: 8,
    tempat_turun: "Madinah",
    arti: "Goncangan",
  },
  {
    nomor: 100,
    nama: "العاديات",
    nama_latin: "Al-'Adiyat",
    jumlah_ayat: 11,
    tempat_turun: "Mekah",
    arti: "Kuda Perang yang Berlari",
  },
  {
    nomor: 101,
    nama: "القارعة",
    nama_latin: "Al-Qari'ah",
    jumlah_ayat: 11,
    tempat_turun: "Mekah",
    arti: "Hari Kiamat",
  },
  {
    nomor: 102,
    nama: "التكاثر",
    nama_latin: "At-Takasur",
    jumlah_ayat: 8,
    tempat_turun: "Mekah",
    arti: "Bermegah-Megahan",
  },
  {
    nomor: 103,
    nama: "العصر",
    nama_latin: "Al-'Asr",
    jumlah_ayat: 3,
    tempat_turun: "Mekah",
    arti: "Masa",
  },
  {
    nomor: 104,
    nama: "الهمزة",
    nama_latin: "Al-Humazah",
    jumlah_ayat: 9,
    tempat_turun: "Mekah",
    arti: "Pengumpat",
  },
  {
    nomor: 105,
    nama: "الفيل",
    nama_latin: "Al-Fil",
    jumlah_ayat: 5,
    tempat_turun: "Mekah",
    arti: "Gajah",
  },
  {
    nomor: 106,
    nama: "قريش",
    nama_latin: "Quraisy",
    jumlah_ayat: 4,
    tempat_turun: "Mekah",
    arti: "Suku Quraisy",
  },
  {
    nomor: 107,
    nama: "الماعون",
    nama_latin: "Al-Ma'un",
    jumlah_ayat: 7,
    tempat_turun: "Mekah",
    arti: "Barang-Barang Berguna",
  },
  {
    nomor: 108,
    nama: "الكوثر",
    nama_latin: "Al-Kausar",
    jumlah_ayat: 3,
    tempat_turun: "Mekah",
    arti: "Nikmat yang Berlimpah",
  },
  {
    nomor: 109,
    nama: "الكافرون",
    nama_latin: "Al-Kafirun",
    jumlah_ayat: 6,
    tempat_turun: "Mekah",
    arti: "Orang-Orang Kafir",
  },
  {
    nomor: 110,
    nama: "النصر",
    nama_latin: "An-Nasr",
    jumlah_ayat: 3,
    tempat_turun: "Madinah",
    arti: "Pertolongan",
  },
  {
    nomor: 111,
    nama: "المسد",
    nama_latin: "Al-Lahab",
    jumlah_ayat: 5,
    tempat_turun: "Mekah",
    arti: "Gejolak Api",
  },
  {
    nomor: 112,
    nama: "الإخلاص",
    nama_latin: "Al-Ikhlas",
    jumlah_ayat: 4,
    tempat_turun: "Mekah",
    arti: "Ikhlas",
  },
  {
    nomor: 113,
    nama: "الفلق",
    nama_latin: "Al-Falaq",
    jumlah_ayat: 5,
    tempat_turun: "Mekah",
    arti: "Waktu Subuh",
  },
  {
    nomor: 114,
    nama: "الناس",
    nama_latin: "An-Nas",
    jumlah_ayat: 6,
    tempat_turun: "Mekah",
    arti: "Manusia",
  },
];
